import type { Metadata } from "next";
import { notFound } from "next/navigation";

import ProfileView from "@/components/Profile";
import { loadProfile } from "@/lib/data";
import { profileShareMetadata } from "@/lib/share";

/**
 * Read per request, not per build.
 *
 * The document is still frozen — one JSON file written once — but a profile generated by
 * the worker an hour after deploy has to resolve, and a revoked one has to stop resolving.
 * Pre-rendering the id list would pin both to whatever existed when the bundle was made.
 */
export const dynamic = "force-dynamic";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  const profile = loadProfile(id);
  if (!profile) return {};
  return profileShareMetadata(
    id,
    profile.evidence_inspected.n_commits_by_subject,
    profile.findings.length,
  );
}

export default async function ProfilePage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const profile = loadProfile(id);
  if (!profile) notFound();
  return <ProfileView profile={profile} />;
}
