import Link from "next/link";

import { listProfileIds, loadProfile } from "@/lib/data";

/**
 * Deliberately not a directory.
 *
 * Phase 1 is single-player: a profile is generated by its subject and shared by link.
 * This index exists for local development only — a browsable list of everyone profiled
 * is a candidate directory, which is an explicit phase-1 non-goal.
 */
export default function Home() {
  const profiles = listProfileIds()
    .map((id) => ({ id, profile: loadProfile(id) }))
    .filter((row) => row.profile !== null);

  return (
    <main className="mx-auto max-w-3xl px-6 py-14">
      <h1 className="text-2xl font-semibold">vouch</h1>
      <p className="mt-3 max-w-prose text-sm leading-relaxed text-slate-600 dark:text-slate-400">
        Evidence-backed engineering capability profiles. A profile is generated by its
        subject and shared as a read-only link; this page lists the snapshots built into
        this bundle and exists for local development.
      </p>

      {profiles.length === 0 ? (
        <p className="mt-8 text-sm text-slate-500">
          No profiles in <code className="font-mono">web/data/profiles/</code>. Generate
          one with <code className="font-mono">vouch report … --web</code>.
        </p>
      ) : (
        <ul className="mt-8 space-y-2">
          {profiles.map(({ id, profile }) => (
            <li key={id}>
              <Link
                href={`/p/${id}`}
                className="text-sm underline underline-offset-4 hover:no-underline"
              >
                {profile!.subject}
              </Link>{" "}
              <span className="text-xs text-slate-500">
                {profile!.evidence_inspected.repo.split("/").slice(-2).join("/")}
              </span>
            </li>
          ))}
        </ul>
      )}
    </main>
  );
}
