import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy · vouch",
  description:
    "What is stored, what never leaves your machine, what a share link discloses, and what revoking can and cannot undo.",
};

const SECTIONS = [
  {
    title: "Minimal GitHub Permissions",
    badge: "read:user Scope",
    content: (
      <>
        <p>
          GitHub sign-in requests only <code className="font-mono text-slate-800 font-semibold">read:user</code> scope. Vouch cannot read private repositories, cannot write code or issues, and cannot alter account settings.
        </p>
        <p className="mt-2 text-slate-600">
          The OAuth token is used solely to list public repositories. Clones run anonymously without credentials.
        </p>
      </>
    ),
  },
  {
    title: "Local-Only Session Telemetry",
    badge: "CLI Engine",
    content: (
      <>
        <p>
          Claude Code logs are processed on your computer by the Vouch CLI. Session files are reduced to closed schema counts.
        </p>
        <p className="mt-2 text-slate-600">
          Raw prompts, file paths, and output text are never transmitted over the network. Web profile analysis processes public git history only and displays <code className="font-mono text-slate-800 font-semibold">not collected</code> for session dimensions.
        </p>
      </>
    ),
  },
  {
    title: "Anonymized Document Payload",
    badge: "Data Isolation",
    content: (
      <>
        <p>
          Repository references are formatted as <code className="font-mono text-slate-800 font-semibold font-bold">org/repo</code>. Full filesystem clone paths are truncated so local client directories remain private.
        </p>
        <p className="mt-2 text-slate-600">
          Profiles list author commit emails to establish identity against git history.
        </p>
      </>
    ),
  },
  {
    title: "Share Link Disclosure & Revocation",
    badge: "Unlisted Links",
    content: (
      <>
        <p>
          Profiles are served with <code className="font-mono text-slate-800 font-semibold">noindex</code> headers. Only people with the explicit link can view the document.
        </p>
        <p className="mt-2 text-slate-600">
          Revoking a profile from your <Link href="/dashboard" className="font-semibold underline underline-offset-4 text-slate-900">dashboard</Link> permanently deletes the document and disables link resolution.
        </p>
      </>
    ),
  },
];

export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-4xl px-6 py-12 animate-fade-in">
      <header className="rounded-2xl border border-slate-200 bg-white p-8 shadow-xs mb-10">
        <p className="text-xs font-bold uppercase tracking-wider text-slate-500">
          Security & Privacy
        </p>
        <h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">
          What is Stored, and What is Not
        </h1>
        <p className="mt-3 max-w-2xl text-sm leading-relaxed text-slate-600">
          Vouch profiles are generated by engineers to represent their own work. Data protection guarantees are enforced by code structure rather than policy.
        </p>
      </header>

      <div className="space-y-6">
        {SECTIONS.map((sec) => (
          <section key={sec.title} className="rounded-2xl border border-slate-200 bg-white p-6 tactile-card">
            <div className="flex items-center justify-between gap-2 mb-3">
              <h2 className="text-lg font-bold text-slate-900">{sec.title}</h2>
              <span className="rounded-md bg-slate-100 px-2.5 py-0.5 text-xs font-semibold text-slate-700 border border-slate-200">
                {sec.badge}
              </span>
            </div>
            <div className="text-sm leading-relaxed text-slate-700">
              {sec.content}
            </div>
          </section>
        ))}
      </div>

      <section className="mt-10 rounded-2xl border border-amber-200 bg-amber-50/40 p-6">
        <h2 className="text-sm font-bold text-amber-900 uppercase tracking-wider">
          Purpose of the Capability Profile
        </h2>
        <p className="mt-2 text-xs text-amber-900/90 leading-relaxed">
          The document is designed to help screeners prepare interview questions based on evidence gaps. It contains no aggregate scores, does not perform candidate ranking, and is meant to support candidate dialogue.
        </p>
      </section>
    </main>
  );
}
